# Generated by Django 4.1.7 on 2023-03-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='videos',
            field=models.ManyToManyField(to='accounts.video'),
        ),
    ]
