# Generated by Django 4.1.7 on 2023-03-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_video_users_user_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='platform',
            field=models.IntegerField(choices=[(1, 'Cda'), (2, 'Ogladajanime'), (3, 'Hdbest')]),
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together={('link', 'platform')},
        ),
    ]
