# Generated by Django 4.1.7 on 2023-03-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_video_platform_alter_video_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='quality',
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='time',
            field=models.TextField(),
            preserve_default=False,
        ),
    ]
